all_symptoms = [
    "runny_or_stuffy_nose",
    "sneezing",
    "sore_throat",
    "mild_cough",
    "mild_headache",
    "low_grade_fever",
    "mild_body_aches_or_fatigue",
    "high_fever",
    "chills",
    "severe_headache",
    "muscle_aches_joint_pain",
    "dry_cough",
    "profound_fatigue_weakness",
    "nasal_congestion",
    "excessive_thirst",
    "frequent_urination",
    "increased_hunger",
    "unintentional_weight_change",
    "blurry_vision",
    "slow_healing_wounds",
    "tingling_numbness_in_extremities",
    "fatigue",
    "no_symptoms_often",
    "occasional_headaches",
    "dizziness",
    "blurred_vision",
    "nosebleeds",
    "fatigue_confusion",
    "difficulty_breathing",
    "wheezing",
    "chest_tightness",
    "coughing_worse_at_night",
    "rapid_breathing",
    "fatigue_during_attacks",
    "sneezing_fits",
    "stuffy_runny_nose_clear",
    "itchy_red_watery_eyes",
    "itchy_throat_or_nose",
    "postnasal_drip",
    "mild_fatigue",
    "persistent_sadness",
    "loss_of_interest",
    "appetite_changes",
    "significant_weight_changes",
    "sleep_disturbances",
    "fatigue_or_loss_of_energy",
    "difficulty_concentrating",
    "feelings_of_guilt",
    "thoughts_of_death_or_suicide",
    "excessive_worry",
    "restlessness",
    "irritability",
    "muscle_tension",
    "memory_loss_short_term",
    "difficulty_finding_words",
    "trouble_completing_familiar_tasks",
    "confusion_time_place",
    "poor_judgment",
    "mood_personality_changes",
    "social_withdrawal",
    "throbbing_headache_one_sided",
    "sensitivity_to_light",
    "sensitivity_to_sound",
    "nausea_vomiting",
    "visual_disturbances_auras",
    "fatigue_difficulty_concentrating",
    "neck_stiffness",
    "persistent_cough_with_mucus",
    "fever_sweating_chills",
    "shortness_of_breath",
    "rapid_shallow_breathing",
    "chest_pain_with_breathing",
    "fatigue_weakness",
    "loss_of_appetite",
    "watery_diarrhea",
    "abdominal_cramps_pain",
    "headache_body_aches",
    "dehydration_symptoms",
    "persistent_cough_3_weeks",
    "coughing_up_blood",
    "night_sweats",
    "fever_chills",
    "unintentional_weight_loss",
    "chest_pain_discomfort",
    "chronic_productive_cough",
    "shortness_of_breath_exertion",
    "wheezing_noisy_breathing",
    "frequent_respiratory_infections",
    "fatigue_reduced_exercise_tolerance",
    "joint_pain_swelling_symmetrical",
    "morning_stiffness_30mins",
    "fatigue_fever_malaise",
    "reduced_range_of_motion",
    "rheumatoid_nodules",
    "joint_deformities_long_term",
    "joint_pain_with_activity",
    "stiffness_less_30mins",
    "reduced_flexibility",
    "bone_spurs",
    "mild_joint_swelling",
    "crepitus_joints",
    "fatigue_sluggishness",
    "weight_gain",
    "cold_intolerance",
    "dry_skin_brittle_hair",
    "constipation",
    "muscle_weakness_aches",
    "depression_low_mood",
    "slow_heart_rate",
    "extreme_fatigue",
    "fever",
    "severe_sore_throat",
    "swollen_lymph_glands",
    "swollen_tonsils",
    "headache",
    "rash",
    "muscle_aches",
    "itchy_blister_like_rash",
    "fatigue_malaise",
    "rash_starts_trunk_spreads",
    "stiff_neck",
    "confusion_concentration_issues",
    "drowsiness_difficulty_waking",
    "seizures_coma"
]
words_map = {
    # Symptoms
    "runny_or_stuffy_nose": "Runny nose or stuffy nose",
    "sneezing": "Sneezing",
    "sore_throat": "Sore throat",
    "mild_cough": "Mild cough",
    "mild_headache": "Mild headache",
    "low_grade_fever": "Low-grade fever",
    "mild_body_aches_or_fatigue": "Mild body aches or fatigue",
    "high_fever": "High fever",
    "chills": "Chills",
    "severe_headache": "Severe headache",
    "muscle_aches_joint_pain": "Muscle aches or joint pain",
    "dry_cough": "Dry cough",
    "profound_fatigue_weakness": "Profound fatigue or weakness",
    "nasal_congestion": "Nasal congestion",
    "excessive_thirst": "Excessive thirst",
    "frequent_urination": "Frequent urination",
    "increased_hunger": "Increased hunger",
    "unintentional_weight_change": "Unintentional weight change",
    "blurry_vision": "Blurry vision",
    "slow_healing_wounds": "Slow-healing wounds",
    "tingling_numbness_in_extremities": "Tingling or numbness in extremities",
    "fatigue": "Fatigue",
    "no_symptoms_often": "No symptoms often",
    "occasional_headaches": "Occasional headaches",
    "dizziness": "Dizziness",
    "blurred_vision": "Blurred vision",
    "nosebleeds": "Nosebleeds",
    "fatigue_confusion": "Fatigue or confusion",
    "difficulty_breathing": "Difficulty breathing",
    "wheezing": "Wheezing",
    "chest_tightness": "Chest tightness",
    "coughing_worse_at_night": "Coughing worse at night",
    "rapid_breathing": "Rapid breathing",
    "fatigue_during_attacks": "Fatigue during attacks",
    "sneezing_fits": "Sneezing fits",
    "stuffy_runny_nose_clear": "Stuffy or runny nose (clear)",
    "itchy_red_watery_eyes": "Itchy, red, watery eyes",
    "itchy_throat_or_nose": "Itchy throat or nose",
    "postnasal_drip": "Postnasal drip",
    "mild_fatigue": "Mild fatigue",
    "persistent_sadness": "Persistent sadness",
    "loss_of_interest": "Loss of interest",
    "appetite_changes": "Appetite changes",
    "significant_weight_changes": "Significant weight changes",
    "sleep_disturbances": "Sleep disturbances",
    "fatigue_or_loss_of_energy": "Fatigue or loss of energy",
    "difficulty_concentrating": "Difficulty concentrating",
    "feelings_of_guilt": "Feelings of guilt",
    "thoughts_of_death_or_suicide": "Thoughts of death or suicide",
    "excessive_worry": "Excessive worry",
    "restlessness": "Restlessness",
    "irritability": "Irritability",
    "muscle_tension": "Muscle tension",
    "memory_loss_short_term": "Memory loss (short term)",
    "difficulty_finding_words": "Difficulty finding words",
    "trouble_completing_familiar_tasks": "Trouble completing familiar tasks",
    "confusion_time_place": "Confusion (time/place)",
    "poor_judgment": "Poor judgment",
    "mood_personality_changes": "Mood or personality changes",
    "social_withdrawal": "Social withdrawal",
    "throbbing_headache_one_sided": "Throbbing headache (one-sided)",
    "sensitivity_to_light": "Sensitivity to light",
    "sensitivity_to_sound": "Sensitivity to sound",
    "nausea_vomiting": "Nausea or vomiting",
    "visual_disturbances_auras": "Visual disturbances or auras",
    "fatigue_difficulty_concentrating": "Fatigue or difficulty concentrating",
    "neck_stiffness": "Neck stiffness",
    "persistent_cough_with_mucus": "Persistent cough with mucus",
    "fever_sweating_chills": "Fever, sweating, chills",
    "shortness_of_breath": "Shortness of breath",
    "rapid_shallow_breathing": "Rapid, shallow breathing",
    "chest_pain_with_breathing": "Chest pain with breathing",
    "fatigue_weakness": "Fatigue or weakness",
    "loss_of_appetite": "Loss of appetite",
    "watery_diarrhea": "Watery diarrhea",
    "abdominal_cramps_pain": "Abdominal cramps or pain",
    "headache_body_aches": "Headache or body aches",
    "dehydration_symptoms": "Dehydration symptoms",
    "persistent_cough_3_weeks": "Persistent cough (3 weeks)",
    "coughing_up_blood": "Coughing up blood",
    "night_sweats": "Night sweats",
    "fever_chills": "Fever and chills",
    "unintentional_weight_loss": "Unintentional weight loss",
    "chest_pain_discomfort": "Chest pain or discomfort",
    "chronic_productive_cough": "Chronic productive cough",
    "shortness_of_breath_exertion": "Shortness of breath on exertion",
    "wheezing_noisy_breathing": "Wheezing or noisy breathing",
    "frequent_respiratory_infections": "Frequent respiratory infections",
    "fatigue_reduced_exercise_tolerance": "Fatigue or reduced exercise tolerance",
    "joint_pain_swelling_symmetrical": "Joint pain or swelling (symmetrical)",
    "morning_stiffness_30mins": "Morning stiffness (30 minutes)",
    "fatigue_fever_malaise": "Fatigue, fever, or malaise",
    "reduced_range_of_motion": "Reduced range of motion",
    "rheumatoid_nodules": "Rheumatoid nodules",
    "joint_deformities_long_term": "Joint deformities (long term)",
    "joint_pain_with_activity": "Joint pain with activity",
    "stiffness_less_30mins": "Stiffness (less than 30 minutes)",
    "reduced_flexibility": "Reduced flexibility",
    "bone_spurs": "Bone spurs",
    "mild_joint_swelling": "Mild joint swelling",
    "crepitus_joints": "Crepitus in joints",
    "fatigue_sluggishness": "Fatigue or sluggishness",
    "weight_gain": "Weight gain",
    "cold_intolerance": "Cold intolerance",
    "dry_skin_brittle_hair": "Dry skin or brittle hair",
    "constipation": "Constipation",
    "muscle_weakness_aches": "Muscle weakness or aches",
    "depression_low_mood": "Depression or low mood",
    "slow_heart_rate": "Slow heart rate",
    "extreme_fatigue": "Extreme fatigue",
    "fever": "Fever",
    "severe_sore_throat": "Severe sore throat",
    "swollen_lymph_glands": "Swollen lymph glands",
    "swollen_tonsils": "Swollen tonsils",
    "headache": "Headache",
    "rash": "Rash",
    "muscle_aches": "Muscle aches",
    "itchy_blister_like_rash": "Itchy, blister-like rash",
    "fatigue_malaise": "Fatigue or malaise",
    "rash_starts_trunk_spreads": "Rash starts on trunk and spreads",
    "stiff_neck": "Stiff neck",
    "confusion_concentration_issues": "Confusion or concentration issues",
    "drowsiness_difficulty_waking": "Drowsiness or difficulty waking",
    "seizures_coma": "Seizures or coma",

    # Diseases
    "common_cold": "Common cold",
    "influenza": "Influenza",
    "type_2_diabetes_mellitus": "Type 2 Diabetes Mellitus",
    "hypertension": "Hypertension",
    "asthma": "Asthma",
    "allergic_rhinitis": "Allergic rhinitis",
    "depression": "Depression",
    "gad": "Generalized Anxiety Disorder (GAD)",
    "alzheimers": "Alzheimer's Disease",
    "migraine": "Migraine",
    "pneumonia": "Pneumonia",
    "gastroenteritis": "Gastroenteritis",
    "tuberculosis": "Tuberculosis",
    "copd": "Chronic Obstructive Pulmonary Disease (COPD)",
    "rheumatoid_arthritis": "Rheumatoid Arthritis",
    "osteoarthritis": "Osteoarthritis",
    "hypothyroidism": "Hypothyroidism",
    "mono": "Mononucleosis",
    "chickenpox": "Chickenpox",
    "meningitis": "Meningitis"
}

reversed_words_map = {v: k for k, v in words_map.items()}